In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

In [2]:
d = np.load('data1.npz')
lat = d['lat'];lon = d['lon'];u=d['u']

In [14]:
def plot_field(lat,lon,u,time,levels=20):
    """
    Generate contour plot of u at particular time
    Use if/as needed
    Input:
    lat,lon: latitude and longitude arrays
    u: full array of wind speed data
    time: time at which wind speed will be plotted (index between 0 and 364)
    levels: number of contour levels in plot
    """
    


    plt.figure()
    plt.contourf(lon,lat,u[time,:,:],levels)
    plt.axis('equal')
    plt.grid()
    plt.xlabel('longitude')
    plt.ylabel('latitude')
    
    return None

In [104]:
A = np.array([speed.flatten() for speed in u])
A = A - A.mean(axis = 0)
U, S, WT = np.linalg.svd(A)
T = U.T
Anew = np.matmul(T, A)

np.linalg.eigh(np.dot(Anew, Anew.T))

EighResult(eigenvalues=array([-1.62694062e-11,  1.60375987e-01,  1.65149781e-01,  1.69825906e-01,
        1.75697090e-01,  1.77233485e-01,  1.87372243e-01,  1.89075333e-01,
        1.90466475e-01,  1.99453900e-01,  2.01082191e-01,  2.03992711e-01,
        2.09128406e-01,  2.12409054e-01,  2.14218624e-01,  2.22470371e-01,
        2.29604546e-01,  2.32249689e-01,  2.35425151e-01,  2.37821386e-01,
        2.43554443e-01,  2.50158619e-01,  2.55392536e-01,  2.64702917e-01,
        2.67255172e-01,  2.77634571e-01,  2.85900296e-01,  2.96979320e-01,
        3.09119117e-01,  3.32877669e-01,  3.43370114e-01,  3.65386540e-01,
        3.83020993e-01,  4.02442306e-01,  4.08378068e-01,  4.26726496e-01,
        4.91331916e-01,  5.02142308e-01,  5.10729201e-01,  5.85264664e-01,
        6.35712307e-01,  7.03306260e-01,  7.61620207e-01,  8.02637702e-01,
        8.58174456e-01,  9.85246502e-01,  1.10773043e+00,  1.28637112e+00,
        1.38888174e+00,  1.41570789e+00,  1.63723039e+00,  1.65228734e+00,
  

In [107]:
np.shape(u[0, :, :])

(16, 144)

(840960,)

In [105]:
np.shape(u)

(365, 16, 144)

In [ ]:
def part2(f,method=2):
    """
    Question 2.1 i)
    Input:
        f: m x n array
        method: 1 or 2, interpolation method to use
    Output:
        fI: interpolated data (using method)
    """

    m,n = f.shape
    fI = np.zeros((m-1,n)) #use/modify as needed

    if method==1:
        fI = 0.5*(f[:-1,:]+f[1:,:])
    else:
        #Coefficients for method 2
        alpha = 0.3
        a = 1.5
        b = 0.1
        
        #coefficients for near-boundary points
        a_bc,b_bc,c_bc,d_bc = (5/16,15/16,-5/16,1/16)

        #add code here
        fI[0, :] = a_bc * f[0, :] + b_bc * f[1, :] + c_bc * f[2, :] + d_bc * f[3, :]
        fI[-1, :] = a_bc * f[-1, :] + b_bc * f[-2, :] + c_bc * f[-3, :] + d_bc * f[-4, :]
        fI[1:-1, :] = 
        alpha*fI[2:, :] + fI[1:-1, :] + alpha*fI[:-2, :]
    return fI #modify as needed

In [111]:
m = 10
n = 10
fI = np.zeros((m-1,n))
a_bc,b_bc,c_bc,d_bc = (5/16,15/16,-5/16,1/16)
f = np.random.randint(0, 10, (10, 10))
fI[0, :] = a_bc * f[0, :] + b_bc * f[1, :] + c_bc * f[2, :] + d_bc * f[3, :]


In [114]:
fI = 0.5*(f[:-1,:]+f[1:,:])
fI

array([[4. , 6. , 0.5, 6. , 1.5, 4.5, 3.5, 5. , 3. , 4. ],
       [8. , 3. , 0.5, 4.5, 3.5, 3.5, 3. , 2.5, 4.5, 4.5],
       [6. , 2.5, 0.5, 2. , 4.5, 0. , 0.5, 6.5, 5. , 4.5],
       [5.5, 2. , 2.5, 4.5, 2. , 3.5, 5. , 7. , 3. , 5. ],
       [6. , 1.5, 4. , 7. , 0. , 5. , 4.5, 7. , 3.5, 1.5],
       [5. , 5.5, 3. , 7. , 0.5, 5.5, 4.5, 7.5, 5.5, 0.5],
       [4.5, 5. , 6. , 5. , 1.5, 7.5, 9. , 5. , 5.5, 3.5],
       [2. , 5. , 5. , 4. , 5.5, 6. , 9. , 3.5, 3.5, 4. ],
       [2.5, 5.5, 3. , 7. , 7. , 4. , 4.5, 2.5, 5.5, 1.5]])

In [115]:
a_bc * f[0, :] + b_bc * f[1, :] + c_bc * f[2, :] + d_bc * f[3, :]

array([5.25  , 6.8125, 0.    , 6.625 , 0.875 , 7.1875, 6.    , 3.0625,
       2.125 , 7.6875])

In [116]:
alpha = 0.3; b = 1.5; c = 0.1

array([[11.  ,  5.55,  0.8 ,  6.9 ,  5.3 ,  4.85,  4.2 ,  5.95,  6.9 ,
         7.05],
       [10.05,  4.  ,  1.4 ,  4.7 ,  6.15,  2.1 ,  2.9 ,  9.35,  7.25,
         7.35],
       [ 9.1 ,  3.2 ,  3.85,  7.2 ,  3.35,  5.  ,  6.5 , 11.05,  5.55,
         6.8 ],
       [ 9.15,  3.75,  5.65, 10.45,  0.75,  7.7 ,  7.35, 11.35,  6.05,
         3.15],
       [ 8.15,  7.45,  6.  , 10.6 ,  0.95,  9.25,  8.55, 11.1 ,  8.2 ,
         2.  ],
       [ 6.6 ,  8.15,  8.4 ,  8.3 ,  3.3 , 10.95, 13.05,  8.3 ,  8.2 ,
         4.85],
       [ 4.1 ,  8.15,  7.7 ,  7.6 ,  8.05,  9.45, 13.05,  5.75,  6.8 ,
         5.5 ]])